default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: furlenco
  password: aRlMTb$V=dug8Ns
  timeout: 5000
  schema_search_path: "public"

development:
  <<: *default
  database: me_development

production:
  pool: 15
  adapter: postgresql
  schema_search_path: "public"